#Logging
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.file.path=logs
spring.application.name=api-go-finy-mobile
spring.profiles.active=api-go-finy-mobile
server.port=9201
server.servlet.context-path=/
jasypt.encryptor.password=lendbiZ@2023
jasypt.encryptor.algorithm=PBEWithMD5AndDES
spring.jpa.properties.hibernate.proc.param_null_passing=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=ENC(PnqIllPsElTEBCMzMKHZRU3DNuGMaEqsWJ9yHIIX5V+I+40TW0Qk6/3X2++zCx9PrcjCcGdSy4I=)
#DBLive
spring.datasource.username=ENC(C8kqb6zJ2hpV/LuQZFDeUA==)
spring.datasource.password=ENC(QwYy7AugLrAHQYJ+ZDvOQPjJ2I+/KDQw)
#DBTest
#spring.datasource.username=ENC(FlZvWRtoMCyHMtto+y/N2AVHfMmc2JK6)
#spring.datasource.password=ENC(Jtofp3WlTzE+KzGUWW37Lrlua2difOYJ)
spring.kafka.bootstrap-servers:42.112.38.102:9201
finy-go.path:http://192.168.100.141:9201/api
#finy-go.path: https://apigotest.finy.vn

