spring.kafka.bootstrap-servers=42.112.38.103:9092
spring.datasource.url=ENC(3nV79dyV6NgqGidlShVtgW6cDbhxaJ2dfjp+Ftfa+L/Xy/VeZXGShpWxoXueYDwNJsAYOhXfGJw=)
#
## Live
##vita | Db@Fn#101
##spring.datasource.username=ENC(C8kqb6zJ2hpV/LuQZFDeUA==)
##spring.datasource.password=ENC(QwYy7AugLrAHQYJ+ZDvOQPjJ2I+/KDQw)

# Test
#vitatest | Finy2024
spring.datasource.username=ENC(2cRqVD/BQt/wuhn+JOf2HpatsTCA8CFP)
spring.datasource.password=ENC(VA/wb64hAfgUzABqC7+Ynu5y1nlXLM45)

finy.url=https://apigateway.lendbiz.vn

econtract.release.version=1
environment=PROD

finy.client.domain=https://econtract.finy.vn
vnpt.domain=https://gateway-bus-econtract.vnpt.vn
vnpt.username=0110351508
vnpt.password=SmCaFn@1508
vnpt.clientid=4C2FF62C5EF27434E0636B20A50AE22A
vnpt.clientsecret=39aa295093f7e5dc22ddccf1cb8b57c9cca3485194c68c48e3d4cfbc2bad21eb
